insert into categories (name) values ('Software Consultant');
insert into categories (name) values ('Marketing Manager');
insert into categories (name) values ('Senior Editor');
insert into categories (name) values ('Project Manager');
insert into categories (name) values ('Cost Accountant');
insert into categories (name) values ('Dental Hygienist');
insert into categories (name) values ('Financial Advisor');
insert into categories (name) values ('Chief Design Engineer');
insert into categories (name) values ('Web Designer II');
insert into categories (name) values ('Senior Quality Engineer');
insert into categories (name) values ('Senior Cost Accountant');
insert into categories (name) values ('Registered Nurse');
insert into categories (name) values ('Social Worker');
insert into categories (name) values ('Registered Nurse');
insert into categories (name) values ('General Manager');
insert into categories (name) values ('Engineer I');
insert into categories (name) values ('Analog Circuit Design manager');
insert into categories (name) values ('Community Outreach Specialist');
insert into categories (name) values ('Research Assistant III');
insert into categories (name) values ('Web Designer III');
insert into categories (name) values ('Geologist IV');
insert into categories (name) values ('Office Assistant III');
insert into categories (name) values ('Financial Analyst');
insert into categories (name) values ('Help Desk Technician');
insert into categories (name) values ('Chief Design Engineer');
insert into categories (name) values ('Senior Quality Engineer');
insert into categories (name) values ('Structural Engineer');
insert into categories (name) values ('Dental Hygienist');
insert into categories (name) values ('Editor');
insert into categories (name) values ('Legal Assistant');
insert into categories (name) values ('Biostatistician II');
insert into categories (name) values ('Human Resources Assistant IV');
insert into categories (name) values ('Media Manager IV');
insert into categories (name) values ('Recruiter');
insert into categories (name) values ('Software Engineer II');
insert into categories (name) values ('Desktop Support Technician');
insert into categories (name) values ('Geological Engineer');
insert into categories (name) values ('Executive Secretary');
insert into categories (name) values ('Account Representative I');
insert into categories (name) values ('Design Engineer');
insert into categories (name) values ('Physical Therapy Assistant');
insert into categories (name) values ('Product Engineer');
insert into categories (name) values ('Product Engineer');
insert into categories (name) values ('Senior Sales Associate');
insert into categories (name) values ('Marketing Manager');
insert into categories (name) values ('Web Developer IV');
insert into categories (name) values ('Software Test Engineer IV');
insert into categories (name) values ('Senior Financial Analyst');
insert into categories (name) values ('Budget/Accounting Analyst II');
insert into categories (name) values ('Design Engineer');
insert into categories (name) values ('Design Engineer');
insert into categories (name) values ('Budget/Accounting Analyst IV');
insert into categories (name) values ('Software Consultant');
insert into categories (name) values ('Librarian');
insert into categories (name) values ('Sales Representative');
insert into categories (name) values ('Automation Specialist II');
insert into categories (name) values ('Business Systems Development Analyst');
insert into categories (name) values ('Statistician III');
insert into categories (name) values ('Database Administrator III');
insert into categories (name) values ('Senior Developer');
insert into categories (name) values ('Office Assistant III');
insert into categories (name) values ('GIS Technical Architect');
insert into categories (name) values ('VP Sales');
insert into categories (name) values ('Database Administrator II');
insert into categories (name) values ('Structural Analysis Engineer');
insert into categories (name) values ('Clinical Specialist');
insert into categories (name) values ('Recruiter');
insert into categories (name) values ('Director of Sales');
insert into categories (name) values ('Sales Representative');
insert into categories (name) values ('Account Executive');
insert into categories (name) values ('Quality Engineer');
insert into categories (name) values ('Community Outreach Specialist');
insert into categories (name) values ('Quality Control Specialist');
insert into categories (name) values ('Information Systems Manager');
insert into categories (name) values ('Database Administrator I');
insert into categories (name) values ('Help Desk Operator');
insert into categories (name) values ('Chief Design Engineer');
insert into categories (name) values ('Registered Nurse');
insert into categories (name) values ('Administrative Officer');
insert into categories (name) values ('Design Engineer');
insert into categories (name) values ('Operator');
insert into categories (name) values ('VP Sales');
insert into categories (name) values ('Nurse Practicioner');
insert into categories (name) values ('VP Quality Control');
insert into categories (name) values ('Developer II');
insert into categories (name) values ('Analyst Programmer');
insert into categories (name) values ('Community Outreach Specialist');
insert into categories (name) values ('Data Coordiator');
insert into categories (name) values ('Sales Associate');
insert into categories (name) values ('Software Engineer II');
insert into categories (name) values ('Programmer I');
insert into categories (name) values ('Associate Professor');
insert into categories (name) values ('Account Executive');
insert into categories (name) values ('Recruiting Manager');
insert into categories (name) values ('GIS Technical Architect');
insert into categories (name) values ('Sales Associate');
insert into categories (name) values ('Product Engineer');
insert into categories (name) values ('Business Systems Development Analyst');
insert into categories (name) values ('Business Systems Development Analyst');
insert into categories (name) values ('Tax Accountant');
