insert into ads (title, description, user_id) values ('At the Earth''s Core', '', 1);
insert into ads (title, description, user_id) values ('Butcher, The (Boucher, Le)', '', 2);
insert into ads (title, description, user_id) values ('Cat Concerto, The', '', 3);
insert into ads (title, description, user_id) values ('Sharknado', '', 4);
insert into ads (title, description, user_id) values ('Coronado', '', 5);
insert into ads (title, description, user_id) values ('Cops and Robbersons', '', 6);
insert into ads (title, description, user_id) values ('Next', '', 7);
insert into ads (title, description, user_id) values ('Finances of the Grand Duke, The (Die Finanzen des Großherzogs)', '', 8);
insert into ads (title, description, user_id) values ('Mujhse Dosti Karoge!', '', 9);
insert into ads (title, description, user_id) values ('Getaway', '', 10);
insert into ads (title, description, user_id) values ('Good Night, and Good Luck.', '', 11);
insert into ads (title, description, user_id) values ('Four Nights with Anna (Cztery noce z Anna)', '', 12);
insert into ads (title, description, user_id) values ('Better Tomorrow, A (Ying hung boon sik)', '', 13);
insert into ads (title, description, user_id) values ('Walk in the Clouds, A', '', 14);
insert into ads (title, description, user_id) values ('First Blood (Rambo: First Blood)', '', 15);
insert into ads (title, description, user_id) values ('Jane Eyre', '', 16);
insert into ads (title, description, user_id) values ('Scream', '', 17);
insert into ads (title, description, user_id) values ('Detroit 9000', '', 18);
insert into ads (title, description, user_id) values ('Triage', '', 19);
insert into ads (title, description, user_id) values ('Outlaw and His Wife, The (a.k.a. You and I) (Berg-Ejvind och hans hustru)', '', 20);
insert into ads (title, description, user_id) values ('Go, Go Second Time Virgin (Yuke yuke nidome no shojo)', '', 21);
insert into ads (title, description, user_id) values ('Sudden Manhattan', '', 22);
insert into ads (title, description, user_id) values ('Hawking', '', 23);
insert into ads (title, description, user_id) values ('Kikujiro (Kikujirô no natsu)', '', 24);
insert into ads (title, description, user_id) values ('Tight Spot', '', 25);
insert into ads (title, description, user_id) values ('Beware of a Holy Whore (Warnung vor einer heiligen Nutte)', '', 26);
insert into ads (title, description, user_id) values ('Let''s Kill Ward''s Wife', '', 27);
insert into ads (title, description, user_id) values ('Turn the River', '', 28);
insert into ads (title, description, user_id) values ('Spy(ies) (Espion(s))', '', 29);
insert into ads (title, description, user_id) values ('Herbie Rides Again', '', 30);
insert into ads (title, description, user_id) values ('Gardens of Stone', '', 31);
insert into ads (title, description, user_id) values ('Cotton Mary', '', 32);
insert into ads (title, description, user_id) values ('Last Song, The', '', 33);
insert into ads (title, description, user_id) values ('Ghost Breakers, The', '', 34);
insert into ads (title, description, user_id) values ('Jimmy Rosenberg: The Father, the Son & the Talent', '', 35);
insert into ads (title, description, user_id) values ('Meat the Truth', '', 36);
insert into ads (title, description, user_id) values ('Live from Baghdad', '', 37);
insert into ads (title, description, user_id) values ('Sada', '', 38);
insert into ads (title, description, user_id) values ('DiG!', '', 39);
insert into ads (title, description, user_id) values ('Batman', '', 40);
insert into ads (title, description, user_id) values ('Illustrated Man, The', '', 41);
insert into ads (title, description, user_id) values ('Vertical Ray of the Sun, The (Mua he chieu thang dung)', '', 42);
insert into ads (title, description, user_id) values ('Nicht alle waren Mörder', '', 43);
insert into ads (title, description, user_id) values ('Futurama: Bender''s Game', '', 44);
insert into ads (title, description, user_id) values ('La Bande du drugstore', '', 45);
insert into ads (title, description, user_id) values ('Ice Age Columbus: Who Were the First Americans?', '', 46);
insert into ads (title, description, user_id) values ('Dead Silent', '', 47);
insert into ads (title, description, user_id) values ('Advanced Style', '', 48);
insert into ads (title, description, user_id) values ('Notorious', '', 49);
insert into ads (title, description, user_id) values ('Unknown Soldier, The (Tuntematon sotilas)', '', 50);
insert into ads (title, description, user_id) values ('Dots', '', 51);
insert into ads (title, description, user_id) values ('X: The Man with the X-Ray Eyes', '', 52);
insert into ads (title, description, user_id) values ('Winners and Sinners (Qi mou miao ji: Wu fu xing)', '', 53);
insert into ads (title, description, user_id) values ('Under the Volcano', '', 54);
insert into ads (title, description, user_id) values ('Black Gold', '', 55);
insert into ads (title, description, user_id) values ('Monster, The (Mostro, Il)', '', 56);
insert into ads (title, description, user_id) values ('Tales from the Darkside: The Movie', '', 57);
insert into ads (title, description, user_id) values ('Blondie Knows Best', '', 58);
insert into ads (title, description, user_id) values ('Wives and Lovers', '', 59);
insert into ads (title, description, user_id) values ('Stitches', '', 60);
insert into ads (title, description, user_id) values ('Looking for Richard', '', 61);
insert into ads (title, description, user_id) values ('Little Shop of Horrors, The', '', 62);
insert into ads (title, description, user_id) values ('G@me', '', 63);
insert into ads (title, description, user_id) values ('Last of the Red Hot Lovers', '', 64);
insert into ads (title, description, user_id) values ('From One Second to the Next', '', 65);
insert into ads (title, description, user_id) values ('Straight Story, The', '', 66);
insert into ads (title, description, user_id) values ('Fantastic Mr. Fox', '', 67);
insert into ads (title, description, user_id) values ('Sea Wife', '', 68);
insert into ads (title, description, user_id) values ('Pecker', '', 69);
insert into ads (title, description, user_id) values ('Head', '', 70);
insert into ads (title, description, user_id) values ('Angels Over Broadway', '', 71);
insert into ads (title, description, user_id) values ('Homegrown', '', 72);
insert into ads (title, description, user_id) values ('Kitchen Party', '', 73);
insert into ads (title, description, user_id) values ('Summer Heights High', '', 74);
insert into ads (title, description, user_id) values ('Prime Suspect 3', '', 75);
insert into ads (title, description, user_id) values ('Pleasure of Being Robbed, The', '', 76);
insert into ads (title, description, user_id) values ('Down and Out in Beverly Hills', '', 77);
insert into ads (title, description, user_id) values ('Indiana Jones and the Kingdom of the Crystal Skull', '', 78);
insert into ads (title, description, user_id) values ('YellowBrickRoad', '', 79);
insert into ads (title, description, user_id) values ('Ai Weiwei: Never Sorry', '', 80);
insert into ads (title, description, user_id) values ('Osmosis (Osmose)', '', 81);
insert into ads (title, description, user_id) values ('Pauline détective', '', 82);
insert into ads (title, description, user_id) values ('Stolen Children (Ladro di bambini, Il)', '', 83);
insert into ads (title, description, user_id) values ('Steamboat Round the Bend', '', 84);
insert into ads (title, description, user_id) values ('Bones', '', 85);
insert into ads (title, description, user_id) values ('Point Break', '', 86);
insert into ads (title, description, user_id) values ('Bang Bang Club, The', '', 87);
insert into ads (title, description, user_id) values ('Prizefighter and the Lady, The', '', 88);
insert into ads (title, description, user_id) values ('I Love You, I Love You (Je t''aime je t''aime)', '', 89);
insert into ads (title, description, user_id) values ('Ten Skies', '', 90);
insert into ads (title, description, user_id) values ('Premium Rush', '', 91);
insert into ads (title, description, user_id) values ('Promise of the Flesh (Yukcheui yaksok)', '', 92);
insert into ads (title, description, user_id) values ('Bigger, Stronger, Faster*', '', 93);
insert into ads (title, description, user_id) values ('For the Love of Movies', '', 94);
insert into ads (title, description, user_id) values ('Soldier''s Girl', '', 95);
insert into ads (title, description, user_id) values ('Street Scenes ', '', 96);
insert into ads (title, description, user_id) values ('Pluto''s Christmas Tree', '', 97);
insert into ads (title, description, user_id) values ('The Puzzle', '', 98);
insert into ads (title, description, user_id) values ('Precious', '', 99);
insert into ads (title, description, user_id) values ('Wrath of the Titans', '', 100);
